In [41]:
# 시뮬레이션 라이브러리 불러오기
import cmath
import math
import matplotlib.pyplot as plt
import numpy as np

import meep as mp

In [42]:
# scaling & refractive index
um_scale = 1/0.500 # 1A = 750 nm

In [43]:
# 해상도 및 사이즈 설정
resolution = 25 # 1 pixel = 30 nm
ar_thktop = round(0.030 * um_scale * 0,2) # ARtop thickness 30 nm
# ar_thk = round(0.030 * um_scale * 3,2) # AR thickness 90 nm
ar_thk = 0
fl_size = round(0.030 * um_scale * 17,2) # focal layer size 510 ~ nm
ml_size = round(0.030 * um_scale * 5,2) # multi layer size 210 ~ 390 nm
el_size = round(0.030 * um_scale,2) # etch layer size 30 nm

dti_thk = round(ar_thk * 2,2) # DTI thickness 
sp_size = round(0.030 * um_scale * 21,2) # subpixel size 630 nm
# sd_size = round(0.030 * um_scale,2) # SiPD size
sd_size = 0

Lpml = 0.40 # PML 영역 크기
pml_layers = [mp.PML(thickness = Lpml, direction = mp.Z)]
Sourcespace = 0.40

# 설계 공간
design_region_width_x = round(sp_size * 4 ,2) # 디자인 영역 x 2520 nm
design_region_width_y = round(sp_size * 4 ,2) # 디자인 영역 y 2520 nm
design_region_height = round(ml_size * 5 + el_size * 4,2) # 디자인 영역 높이 z

# 전체 공간
Sx = design_region_width_x
Sy = design_region_width_y
Sz = round(Lpml + Sourcespace + ar_thktop + design_region_height + fl_size + ar_thk + sd_size + Lpml,2)
cell_size = mp.Vector3(Sx, Sy, Sz)

In [44]:
# 파장, 주파수 설정
wavelengths = np.linspace(0.425*um_scale, 0.655*um_scale, 24) 
frequencies = 1/wavelengths
nf = len(frequencies) # number of frequencies

In [45]:
# source 설정
width = 0.4

fcen_red = 1/(0.625*um_scale)
fwidth_red = fcen_red * width

fcen_green = 1/(0.545*um_scale)
fwidth_green = fcen_green * width

fcen_blue = 1/(0.455*um_scale)
fwidth_blue = fcen_blue * width

src_0 = mp.GaussianSource(frequency=fcen_red, fwidth=fwidth_red, is_integrated=True)

src_1 = mp.GaussianSource(frequency=fcen_green, fwidth=fwidth_green, is_integrated=True)

src_2 = mp.GaussianSource(frequency=fcen_blue, fwidth=fwidth_blue, is_integrated=True)

source_center = [0, 0, round(Sz / 2 - Lpml - Sourcespace / 2,2) ] # Source 위치
source_size = mp.Vector3(Sx, Sy, 0)

source = [mp.Source(src_0, component=mp.Ex, size=source_size, center=source_center,amplitude=1.0038735638222),
            mp.Source(src_1, component=mp.Ex, size=source_size, center=source_center,amplitude=1),
            mp.Source(src_2, component=mp.Ex, size=source_size, center=source_center,amplitude=1.41915621661661)]


In [46]:
sim = mp.Simulation(
    cell_size=cell_size, 
    boundary_layers=pml_layers,
    sources=source,
    resolution=resolution,
    k_point = mp.Vector3(0,0,0)
)

In [47]:
tran_Ex_r0 = sim.add_dft_fields([mp.Ex], frequencies[17], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r1 = sim.add_dft_fields([mp.Ex], frequencies[18], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r2 = sim.add_dft_fields([mp.Ex], frequencies[19], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r3 = sim.add_dft_fields([mp.Ex], frequencies[20], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r4 = sim.add_dft_fields([mp.Ex], frequencies[21], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r5 = sim.add_dft_fields([mp.Ex], frequencies[22], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_r6 = sim.add_dft_fields([mp.Ex], frequencies[23], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)

tran_Ex_g0 = sim.add_dft_fields([mp.Ex], frequencies[9], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g1 = sim.add_dft_fields([mp.Ex], frequencies[10], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g2 = sim.add_dft_fields([mp.Ex], frequencies[11], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g3 = sim.add_dft_fields([mp.Ex], frequencies[12], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g4 = sim.add_dft_fields([mp.Ex], frequencies[13], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g5 = sim.add_dft_fields([mp.Ex], frequencies[14], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_g6 = sim.add_dft_fields([mp.Ex], frequencies[15], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)

tran_Ex_b0 = sim.add_dft_fields([mp.Ex], frequencies[0], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b1 = sim.add_dft_fields([mp.Ex], frequencies[1], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b2 = sim.add_dft_fields([mp.Ex], frequencies[2], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b3 = sim.add_dft_fields([mp.Ex], frequencies[3], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b4 = sim.add_dft_fields([mp.Ex], frequencies[4], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b5 = sim.add_dft_fields([mp.Ex], frequencies[5], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)
tran_Ex_b6 = sim.add_dft_fields([mp.Ex], frequencies[6], 0 , 1, center=mp.Vector3(0, 0, 0), size=mp.Vector3(0.01, 0.01, 0), yee_grid=True)

pt = mp.Vector3(0, 0, -Sz/2 + Lpml) 
sim.run(until_after_sources=mp.stop_when_fields_decayed(10,mp.Ex,pt,1e-5))


array0_r = sim.get_dft_array(tran_Ex_r0, mp.Ex, 0)
array1_r = sim.get_dft_array(tran_Ex_r1, mp.Ex, 0)
array2_r = sim.get_dft_array(tran_Ex_r2, mp.Ex, 0)
array3_r = sim.get_dft_array(tran_Ex_r3, mp.Ex, 0)
array4_r = sim.get_dft_array(tran_Ex_r4, mp.Ex, 0)
array5_r = sim.get_dft_array(tran_Ex_r5, mp.Ex, 0)
array6_r = sim.get_dft_array(tran_Ex_r6, mp.Ex, 0)

array0_g = sim.get_dft_array(tran_Ex_g0, mp.Ex, 0)
array1_g = sim.get_dft_array(tran_Ex_g1, mp.Ex, 0)
array2_g = sim.get_dft_array(tran_Ex_g2, mp.Ex, 0)
array3_g = sim.get_dft_array(tran_Ex_g3, mp.Ex, 0)
array4_g = sim.get_dft_array(tran_Ex_g4, mp.Ex, 0)
array5_g = sim.get_dft_array(tran_Ex_g5, mp.Ex, 0)
array6_g = sim.get_dft_array(tran_Ex_g6, mp.Ex, 0)

array0_b = sim.get_dft_array(tran_Ex_b0, mp.Ex, 0)
array1_b = sim.get_dft_array(tran_Ex_b1, mp.Ex, 0)
array2_b = sim.get_dft_array(tran_Ex_b2, mp.Ex, 0)
array3_b = sim.get_dft_array(tran_Ex_b3, mp.Ex, 0)
array4_b = sim.get_dft_array(tran_Ex_b4, mp.Ex, 0)
array5_b = sim.get_dft_array(tran_Ex_b5, mp.Ex, 0)
array6_b = sim.get_dft_array(tran_Ex_b6, mp.Ex, 0)



-----------
Initializing structure...
time for choose_chunkdivision = 2.40803e-05 s
Working in 3D dimensions.
Computational cell is 5.04 x 5.04 x 3.96 with resolution 25
time for set_epsilon = 1.45156 s
-----------
on time step 78 (time=1.56), 0.0517097 s/step
on time step 179 (time=3.58), 0.0396178 s/step
on time step 281 (time=5.62), 0.0394196 s/step
on time step 388 (time=7.76), 0.0374797 s/step
on time step 496 (time=9.92), 0.0371548 s/step
field decay(t = 10.02): 0.012466456571469308 / 0.012466456571469308 = 1.0
on time step 600 (time=12), 0.0386043 s/step
on time step 695 (time=13.9), 0.0424286 s/step
on time step 801 (time=16.02), 0.0378718 s/step
on time step 901 (time=18.02), 0.0402312 s/step
field decay(t = 20.04): 0.937493518673322 / 0.937493518673322 = 1.0
on time step 1010 (time=20.2), 0.0369134 s/step
on time step 1115 (time=22.3), 0.0383685 s/step
on time step 1212 (time=24.24), 0.0412635 s/step
on time step 1310 (time=26.2), 0.0408731 s/step
on time step 1409 (time=28.1

In [48]:
print(np.abs(array0_r) ** 2 +
np.abs(array1_r) ** 2 +
np.abs(array2_r) ** 2 +
np.abs(array3_r) ** 2 +
np.abs(array4_r) ** 2 +
np.abs(array5_r) ** 2 +
np.abs(array6_r) ** 2 )

print(np.abs(array0_g) ** 2 +
np.abs(array1_g) ** 2 +
np.abs(array2_g) ** 2 +
np.abs(array3_g) ** 2 +
np.abs(array4_g) ** 2 +
np.abs(array5_g) ** 2 +
np.abs(array6_g) ** 2 )

print(np.abs(array0_b) ** 2 +
np.abs(array1_b) ** 2 +
np.abs(array2_b) ** 2 +
np.abs(array3_b) ** 2 +
np.abs(array4_b) ** 2 +
np.abs(array5_b) ** 2 +
np.abs(array6_b) ** 2 )



[[2.91042603 2.91042603 2.91042603]
 [2.91042603 2.91042603 2.91042603]]
[[2.98497442 2.98497442 2.98497442]
 [2.98497442 2.98497442 2.98497442]]
[[2.94025321 2.94025321 2.94025321]
 [2.94025321 2.94025321 2.94025321]]


In [49]:
print(math.sqrt(2.91629218/2.89382989))

1.0038735638222


In [50]:
print(math.sqrt(2.91629218/1.44800688))

1.41915621661661
